server:
  port: 80

spring:
  application:
    name: SPRINGCLOUD-CONSUMER-LOADBALANCE-RIBBON-CUSTOM-STRATEGY-HARDCODE-ORDER80 #注意:服务名不要出现_
  devtools:
    restart:
      enabled: true
  logging:
    level: info
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost #服务信息详细Address栏目显示的值,如果不配置,Address显示为当前计算机名称
        service-name: ${spring.application.name}

#服务提供方信息
service:
  provider:
    name: SPRINGCLOUD-PROVIDER-PAYMENT-SERVICE-CLUSTER
    url: http://${service.provider.name} #服务提供方名称

