server:
  port: 80

spring:
  application:
    name: SPRINGCLOUD-CONSUMER-LOADBALANCE-RIBBON-CONFIGURATION-ORDER80 #注意:服务名不要出现_
  devtools:
    restart:
      enabled: true
  logging:
    level: info
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost #服务信息详细Address栏目显示的值,如果不配置,Address显示为当前计算机名称
        service-name: ${spring.application.name}
  #  zipkin:
#      base-url: http://localhost:9411
#  sleuth:
#    sampler:
#    #采样率值介于 0 到 1 之间，1 则表示全部采集
#    probability: 1

#服务提供方注册名称
SPRINGCLOUD-PROVIDER-PAYMENT-SERVICE-CLUSTER: #服务提供方名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #Ribbon负载均衡规则类所在的路径,自带七种规则,也可以是自定位规则的类所在的路径

#服务提供方信息
service:
  provider:
    name: SPRINGCLOUD-PROVIDER-PAYMENT-SERVICE-CLUSTER  #服务提供方名称
    url: http://${service.provider.name} #服务提供方调用地址
